### ISSUE TITLE
questions with respect to construction of ark module.

### ISSUE THREAD

**Issue by d12306** [matbambbang/sspnet#1]
Hello, @matbambbang , thanks for releasing the code, 
I found when we construct the ``cifar_model_ark" model in the ./model/cifar10.py, line 369-374, if the block type is "res",'ssp2" and "ssp3", then the model after construction is the same because we will use the default setting from line 103 in ./model/cifar10.py, so if this is the case, I wonder why you use the same config here when we have different block name?

If I understand this correctly, these lines ( line 369-374) can be removed since you just want to use the different blocks in different stages?

Please correct me if I am wrong.

**Comment by matbambbang** [comment]
The argument 'block' in the ./model/cifar10.py, line 103 is not used to construct the model. If you want to use the other configuration, such as Res-SSP3-SSP2 (in our paper, we used Ark-Res-SSP2), you should specify the argument 'blokck1', 'block2', and 'block3' in the ./model/cifar10.py, line 368. If you have any more questions, feel free to ask about it.
